;; Org Mode
(require 'org-install)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-switchb)
(setq org-completion-use-ido t)
;(setq org-outline-path-complete-in-steps t)
(setq org-complete-tags-always-offer-all-agenda-tags t)
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
;'(org-disputed-keys (quote (([(shift up)] . [(meta p)])
;                            ([(shift down)] . [(meta n)])
;                            ([(shift left)] . [(meta -)])
;                            ([(shift right)] . [(meta +)])
;                            ([(control shift right)] . [(meta shift +)])
;                            ([(control shift left)] . [(meta shift -)])
;                            ([(control return)] . [(control meta return)]))))
; '(org-replace-disputed-keys t)
